const actionTypes: FuelStationsNS.IActionTypes = {
    FUEL_STATIONS_CLEAR_STATE: 'FUEL_STATIONS_CLEAR_STATE',
    FUEL_STATIONS_SET_FETCH_ERROR: 'FUEL_STATIONS_SET_FETCH_ERROR',
    FUEL_STATIONS_SET_INITIAL_DATA: 'FUEL_STATIONS_SET_INITIAL_DATA',
    FUEL_STATIONS_SET_LOADER: 'FUEL_STATIONS_SET_LOADER',
    FUEL_STATIONS_SET_SELECTED_FUEL_STATION: 'FUEL_STATIONS_SET_SELECTED_FUEL_STATION',
};

export default actionTypes;
