const actionTypes: LoginNS.IActionTypes = {
    LOGIN_ON_SUBMIT_CREDENTIALS: 'LOGIN_ON_SUBMIT_CREDENTIALS',
    LOGIN_SET_EMAIL: 'LOGIN_SET_EMAIL',
    LOGIN_SET_INPUT_VALIDATION_ERROR: 'LOGIN_SET_INPUT_VALIDATION_ERROR',
    LOGIN_SET_LOGIN_ERROR: 'LOGIN_SET_LOGIN_ERROR',
    LOGIN_SET_PASSWORD: 'LOGIN_SET_PASSWORD',
    LOGIN_CLEAR_STATE: 'LOGIN_CLEAR_STATE',
    LOGIN_SET_LOADER: 'LOGIN_SET_LOADER',
    LOGIN_SET_SHOW_ERROR_MODAL: 'LOGIN_SET_SHOW_ERROR_MODAL',
};

export default actionTypes;
