const actionTypes: ProfileNS.IActionTypes = {
    PROFILE_SET_INITIAL_DATA:'PROFILE_SET_INITIAL_DATA',
    PROFILE_SET_LOADER: 'PROFILE_SET_LOADER',
    PROFILE_SET_FETCH_ERROR: 'PROFILE_SET_FETCH_ERROR',
    PROFILE_CLEAR_STATE: 'PROFILE_CLEAR_STATE',
    PROFILE_ON_CLICK_LOGOUT: 'PROFILE_ON_CLICK_LOGOUT',
    PROFILE_SET_INPUT_VALIDATION_ERROR: 'PROFILE_SET_INPUT_VALIDATION_ERROR',
    PROFILE_SET_ADD_MONEY_INPUT: 'PROFILE_SET_ADD_MONEY_INPUT',
    PROFILE_SET_ADD_MONEY_URL: 'PROFILE_SET_ADD_MONEY_URL',
    PROFILE_SET_ADD_MONEY_ERROR: 'PROFILE_SET_ADD_MONEY_ERROR',
    PROFILE_SET_ADD_MONEY_LOADER: 'PROFILE_SET_ADD_MONEY_LOADER',
};

export default actionTypes;
