const actionTypes: ProfileNS.IActionTypes = {
    PROFILE_SET_INITIAL_DATA:'PROFILE_SET_INITIAL_DATA',
    PROFILE_SET_LOADER: 'PROFILE_SET_LOADER',
    PROFILE_SET_FETCH_ERROR: 'PROFILE_SET_FETCH_ERROR',
    PROFILE_CLEAR_STATE: 'PROFILE_CLEAR_STATE',
    PROFILE_ON_CLICK_LOGOUT: 'PROFILE_ON_CLICK_LOGOUT',
};

export default actionTypes;
