const actionTypes: RegisterNS.IActionTypes = {
    REGISTER_CLEAR_STATE: 'REGISTER_CLEAR_STATE',
    REGISTER_ON_SUBMIT_CREDENTIALS: 'REGISTER_ON_SUBMIT_CREDENTIALS',
    REGISTER_SET_EMAIL: 'REGISTER_SET_EMAIL',
    REGISTER_SET_INPUT_VALIDATION_ERROR: 'REGISTER_SET_INPUT_VALIDATION_ERROR',
    REGISTER_SET_LOADER: 'REGISTER_SET_LOADER',
    REGISTER_SET_MOBILE_NUMBER: 'REGISTER_SET_MOBILE_NUMBER',
    REGISTER_SET_NAME: 'REGISTER_SET_NAME',
    REGISTER_SET_PASSWORD: 'REGISTER_SET_PASSWORD',
    REGISTER_SET_REGISTER_ERROR: 'REGISTER_SET_REGISTER_ERROR',
    REGISTER_SET_SHOW_ERROR_MODAL: 'REGISTER_SET_SHOW_ERROR_MODAL',
};

export default actionTypes;
